"""
AUTO-GENERATED FILE - DO NOT EDIT

This file is automatically generated from the JSON Schema.
Source: packages/schemas/booking/v0/booking.schema.json

To regenerate this file, run:
    ./tools/generate-types/generate-py.sh

Any manual changes will be overwritten on the next generation.
"""

# generated by datamodel-codegen:
#   filename:  booking.schema.json
#   timestamp: 2026-01-08T04:16:20+00:00

from __future__ import annotations

from datetime import date
from typing import Annotated, Optional, Union

from pydantic import BaseModel, ConfigDict, EmailStr, Field, RootModel


class Contact(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Contact phone number',
            pattern='^[\\+]?[(]?[0-9]{1,4}[)]?[-\\s\\.]?[(]?[0-9]{1,4}[)]?[-\\s\\.]?[0-9]{1,9}$',
        ),
    ]


class RestaurantBookingRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    restaurantId: Annotated[
        str, Field(description='Unique identifier of the restaurant')
    ]
    date: Annotated[date, Field(description='Booking date (YYYY-MM-DD)')]
    time: Annotated[
        str,
        Field(
            description='Booking time (HH:mm)', pattern='^([01]\\d|2[0-3]):[0-5]\\d$'
        ),
    ]
    partySize: Annotated[int, Field(description='Number of guests', ge=1)]
    contact: Annotated[
        Union[EmailStr, Contact],
        Field(description='Contact information - either email or phone number'),
    ]
    specialRequests: Annotated[
        Optional[str],
        Field(description='Optional notes for the restaurant', max_length=500),
    ] = None
