/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated from the JSON Schema.
 * Source: packages/schemas/booking/v0/booking.schema.json
 *
 * To regenerate this file, run:
 *   ./tools/generate-types/generate-ts.sh
 *
 * Any manual changes will be overwritten on the next generation.
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RestaurantBookingRequest {
  /**
   * Unique identifier of the restaurant
   */
  restaurantId: string;
  /**
   * Booking date (YYYY-MM-DD)
   */
  date: string;
  /**
   * Booking time (HH:mm)
   */
  time: string;
  /**
   * Number of guests
   */
  partySize: number;
  /**
   * Contact information - either email or phone number
   */
  contact: string;
  /**
   * Optional notes for the restaurant
   */
  specialRequests?: string;
}
