#!/usr/bin/env bash

# Python Type Generation Script
# Generates Python types from JSON Schema
# Target: backend/types/booking.py

set -e

# Get the root directory (two levels up from this script)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

SCHEMA_FILE="$ROOT_DIR/packages/schemas/booking/v0/booking.schema.json"
OUTPUT_FILE="$ROOT_DIR/backend/types/booking.py"

echo "Generating Python types from schema..."
echo "Schema: $SCHEMA_FILE"
echo "Output: $OUTPUT_FILE"

# Check if schema exists
if [ ! -f "$SCHEMA_FILE" ]; then
  echo "Error: Schema file not found at $SCHEMA_FILE"
  exit 1
fi

# Generate types using datamodel-code-generator
TMP_OUTPUT=$(mktemp)

# Use the Python 3.12 venv for code generation (to avoid Python 3.14 compatibility issues)
if [ -f "$ROOT_DIR/.venv-codegen/bin/datamodel-codegen" ]; then
  DATAMODEL_CMD="$ROOT_DIR/.venv-codegen/bin/datamodel-codegen"
else
  # Fall back to system installation
  DATAMODEL_CMD="datamodel-codegen"
fi

$DATAMODEL_CMD \
  --input "$SCHEMA_FILE" \
  --input-file-type jsonschema \
  --output "$TMP_OUTPUT" \
  --output-model-type pydantic_v2.BaseModel \
  --use-annotated \
  --target-python-version 3.12

# Add auto-generated warning header and write to output file
cat > "$OUTPUT_FILE" << 'EOF'
"""
AUTO-GENERATED FILE - DO NOT EDIT

This file is automatically generated from the JSON Schema.
Source: packages/schemas/booking/v0/booking.schema.json

To regenerate this file, run:
    ./tools/generate-types/generate-py.sh

Any manual changes will be overwritten on the next generation.
"""

EOF

# Append the generated types
cat "$TMP_OUTPUT" >> "$OUTPUT_FILE"

# Clean up
rm "$TMP_OUTPUT"

echo "✓ Python types generated successfully!"
