#!/usr/bin/env bash

# TypeScript Type Generation Script
# Generates TypeScript types from JSON Schema
# Target: frontend/fetch-business-onboarding/types/booking.ts

set -e

# Get the root directory (two levels up from this script)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

SCHEMA_FILE="$ROOT_DIR/packages/schemas/booking/v0/booking.schema.json"
OUTPUT_FILE="$ROOT_DIR/frontend/fetch-business-onboarding/types/booking.ts"

echo "Generating TypeScript types from schema..."
echo "Schema: $SCHEMA_FILE"
echo "Output: $OUTPUT_FILE"

# Check if schema exists
if [ ! -f "$SCHEMA_FILE" ]; then
  echo "Error: Schema file not found at $SCHEMA_FILE"
  exit 1
fi

# Generate types using json-schema-to-typescript
# We'll use npx to run it without requiring global installation
TMP_OUTPUT=$(mktemp)

npx --yes json-schema-to-typescript@latest "$SCHEMA_FILE" > "$TMP_OUTPUT"

# Add auto-generated warning header and write to output file
cat > "$OUTPUT_FILE" << 'EOF'
/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated from the JSON Schema.
 * Source: packages/schemas/booking/v0/booking.schema.json
 *
 * To regenerate this file, run:
 *   ./tools/generate-types/generate-ts.sh
 *
 * Any manual changes will be overwritten on the next generation.
 */

EOF

# Append the generated types
cat "$TMP_OUTPUT" >> "$OUTPUT_FILE"

# Clean up
rm "$TMP_OUTPUT"

echo "✓ TypeScript types generated successfully!"
